use crate::config::Language;

pub fn tr(key: &str, lang: &Language) -> String {
    match lang {
        Language::English => match key {
            // --- Launcher ---
            "launch_start" => "START ENGINE",
            "launch_sett" => "SETTINGS",
            "launch_docs" => "DOCUMENTATION",
            "launch_cred" => "CREDITS / AUTHOR",
            "launch_upd" => "CHECK UPDATES",
            "launch_exit" => "EXIT",
            
            "launch_menu_title" => " MAIN MENU ",
            "launch_info_title" => " INFORMATION ",
            "launch_ready" => "READY TO RACE",
            "launch_conn_desc" => "Connect to Assetto Corsa Shared Memory.\nMake sure the game is running.",
            "launch_stat" => "Connection Status:",
            "launch_detect" => "DETECTED",
            "launch_wait" => "WAITING...",
            
            "launch_conf_title" => "APP CONFIGURATION",
            "launch_conf_desc" => "Press ENTER to open settings.",
            "launch_lang_title" => "INTERFACE LANGUAGE",
            "launch_lang_desc" => "Use LEFT / RIGHT arrows to switch language instantly.",
            "launch_doc_title" => "USER MANUAL",
            "launch_nav" => "Navigation:",
            "launch_nav_desc" => " F1-F7 : Switch Tabs\n Q     : Return / Quit\n Arrows: Navigate",
            "launch_feat" => "Features:",
            "launch_feat_desc" => " • Telemetry: Live graphs\n • Engineer: Real-time advice\n • Analysis: Lap comparison",
            "launch_cred_title" => "CREDITS & AUTHOR",
            "launch_ver" => "Version 3.1.0 (Stable)",
            "launch_created" => "Created by:",
            "launch_thanks" => "Special thanks to:",
            "launch_upd_title" => "SYSTEM UPDATE",
            "launch_upd_check" => "Checking remote server...",
            "launch_upd_ok" => "You have the latest version.",
            "launch_shut_title" => "SHUTDOWN",
            "launch_safe" => "Data is saved automatically.\nPress ENTER to close.",
            "launch_on" => "✓ System Online",
            "launch_hint" => "Press Q to Quit",

            // --- Settings ---
            "settings_title" => "SETTINGS",
            "cat_general" => "General",
            "cat_eng" => "Engineer & Race",
            "cat_units" => "Units",
            "cat_alerts" => "Alerts",
            
            "lang" => "Language",
            "update_rate" => "Update Rate",
            "history_size" => "History Size",
            "auto_save" => "Auto Save",
            
            "cfg_shift" => "Shift Beep Offset",
            "cfg_fuel_safe" => "Fuel Safety Margin",
            "cfg_opt_press" => "Target Pressure",
            "cfg_logs" => "Disk Logging",
            
            "unit_pressure" => "Pressure Unit",
            "unit_temp" => "Temperature Unit",
            
            "alert_t_min" => "Min Tyre Temp",
            "alert_t_max" => "Max Tyre Temp",
            "alert_b_max" => "Max Brake Temp",
            "alert_fuel" => "Fuel Warning",
            "alert_wear" => "Wear Warning",
            
            // --- Other ---
            "footer_connected" => "CONNECTED",
            "footer_disconnected" => "DISCONNECTED",
            "footer_keys" => "F1-F7: Tabs | Q: Menu",
            "tab_dash" => "DASHBOARD",
            "tab_tele" => "TELEMETRY",
            "tab_eng" => "ENGINEER",
            "tab_setup" => "SETUP",
            "tab_anal" => "ANALYSIS",
            "tab_strat" => "STRATEGY",
            "tab_set" => "SETTINGS",
            
            // --- Analysis ---
            "anal_waiting" => "No laps yet.",
            "anal_laps_list" => "Laps History",
            "anal_speed_comp" => "Speed Trace",
            "anal_deep" => "Driving Analysis",
            "anal_stability" => "Stability",
            "anal_time" => "Time",
            "anal_max_spd" => "Max Spd",
            "anal_avg_spd" => "Avg Spd",
            "anal_fuel_used" => "Fuel",
            "anal_time_lost" => "Loss Analysis",
            "anal_self_title" => "Self Analysis",
            "lbl_trail" => "Trail Braking",
            "lbl_coast" => "Coasting",
            "lbl_overlap" => "Overlap",
            "lbl_smooth" => "Smoothness",
            "lbl_under" => "Understeer",
            "lbl_over" => "Oversteer",
            "lbl_lock" => "Lockups",

            // --- Strategy ---
            "strat_fuel_title" => "Fuel Calc",
            "strat_tyres_title" => "Tyres",
            "strat_env_title" => "Environment",
            "strat_cons" => "Avg Cons.",
            "strat_laps_rem" => "Laps Rem.",
            "strat_fuel_rem" => "Fuel Rem.",
            "strat_needed" => "Fuel Needed",
            "strat_delta" => "Delta",
            "strat_grip" => "Grip",
            "strat_air" => "Air",
            "strat_road" => "Road",
            "strat_wind" => "Wind",

            // --- Telemetry ---
            "graph_speed_rpm" => "Speed/RPM",
            "graph_inputs" => "Inputs",
            "graph_gforce" => "G-Force",
            "graph_steering" => "Steer",
            "no_data" => "Waiting...",
            "tele_friction" => "Friction",
            "tele_car" => "Car State",
            "tele_eng_report" => "Report",
            "tele_errors" => "Errors",
            "lbl_lat_g" => "Lat G",
            "lbl_lon_g" => "Lon G",
            "lbl_clutch" => "Clutch",
            "lbl_steer" => "Angle",
            "lbl_pred_lap" => "Pred.",
            "lbl_fuel_rem" => "Fuel",
            "tele_map" => "Map",
            "tele_map_waiting" => "Drive lap...",
            "tele_live" => "Live",
            
            // --- Dashboard ---
            "dash_tyre_status" => "TYRES",
            "dash_perf" => "PERF",
            "dash_session" => "SESSION",
            "dash_quick" => "QUICK",
            "avg_press" => "Avg P",
            "avg_temp" => "Avg T",
            "avg_wear" => "Wear",
            "lbl_speed" => "SPD",
            "lbl_rpm" => "RPM",
            "lbl_gear" => "GEAR",
            "lbl_delta" => "DELTA",
            "lbl_throttle" => "THR",
            "lbl_brake" => "BRK",
            "lbl_car" => "Car",
            "lbl_track" => "Track",
            "lbl_session" => "Sess",
            "lbl_laps" => "Laps",
            "lbl_pos" => "Pos",
            "lbl_fuel" => "Fuel",
            "lbl_tc" => "TC",
            "lbl_abs" => "ABS",
            "lbl_map" => "Map",
            
            // --- Engineer ---
            "eng_recs" => "ADVICE",
            "eng_analysis" => "STYLE",
            "eng_good" => "All good.",
            "eng_push" => "Push!",
            "eng_action" => "Action",
            "eng_smooth" => "Smooth",
            "eng_steer" => "Steer",
            "eng_aggr" => "Aggr",
            "eng_trail" => "Trail",
            "eng_lock" => "Lock",
            "eng_spin" => "Spin",
            
            // --- Setup ---
            "set_list" => "SETUPS",
            "set_compare" => "COMPARE",
            "set_param" => "Param",
            "set_val" => "Val",
            "set_recom" => "Rec",
            "set_diff" => "Diff",
            "set_no_file" => "No files",
            "grp_gen" => "GEN",
            "grp_tyres" => "TYRES",
            "grp_aero" => "AERO",
            "grp_align" => "ALIGN",
            "grp_susp" => "SUSP",
            "grp_damp" => "DAMP",
            "grp_driv" => "DRIV",
            "grp_brake" => "BRK",
            "p_fuel" => "Fuel",
            "p_bias" => "Bias",
            "p_limiter" => "Limiter",
            "p_press" => "Press",
            "p_wing" => "Wing",
            "p_camber" => "Camber",
            "p_toe" => "Toe",
            "p_spring" => "Spring",
            "p_rod" => "Height",
            "p_arb" => "ARB",
            "p_bump" => "Bump",
            "p_reb" => "Reb",
            "p_f_bump" => "F.Bump",
            "p_f_reb" => "F.Reb",
            "p_diff_p" => "Diff P",
            "p_diff_c" => "Diff C",
            "p_gear" => "Gear",
            "p_final" => "Final",
            
            "view_setup" => "Setup",
            "view_anal" => "Analysis",
            "view_strat" => "Strategy",
            "view_tele" => "Telemetry",
            
            _ => key,
        }.to_string(),
        
        Language::Russian => match key {
            // --- Лаунчер ---
            "launch_start" => "ЗАПУСК ДВИГАТЕЛЯ",
            "launch_sett" => "НАСТРОЙКИ",
            "launch_docs" => "ДОКУМЕНТАЦИЯ",
            "launch_cred" => "АВТОРЫ / ИНФО",
            "launch_upd" => "ПРОВЕРИТЬ ОБНОВЛЕНИЯ",
            "launch_exit" => "ВЫХОД",
            
            "launch_menu_title" => " ГЛАВНОЕ МЕНЮ ",
            "launch_info_title" => " ИНФОРМАЦИЯ ",
            "launch_ready" => "ГОТОВ К ГОНКЕ",
            "launch_conn_desc" => "Подключение к памяти Assetto Corsa.\nУбедитесь, что игра запущена.",
            "launch_stat" => "Статус подключения:",
            "launch_detect" => "ОБНАРУЖЕНО",
            "launch_wait" => "ОЖИДАНИЕ...",
            
            "launch_conf_title" => "КОНФИГУРАЦИЯ",
            "launch_conf_desc" => "Нажмите ENTER для настроек.",
            "launch_lang_title" => "ЯЗЫК ИНТЕРФЕЙСА",
            "launch_lang_desc" => "Используйте стрелки ВЛЕВО / ВПРАВО для смены языка.",
            "launch_doc_title" => "РУКОВОДСТВО",
            "launch_nav" => "Навигация:",
            "launch_nav_desc" => " F1-F7 : Вкладки\n Q     : Назад / Выход\n Стрелки: Меню",
            "launch_feat" => "Возможности:",
            "launch_feat_desc" => " • Телеметрия: Графики\n • Инженер: Советы\n • Анализ: Сравнение",
            "launch_cred_title" => "АВТОРЫ И БЛАГОДАРНОСТИ",
            "launch_ver" => "Версия 3.1.0 (Stable)",
            "launch_created" => "Создатель:",
            "launch_thanks" => "Благодарности:",
            "launch_upd_title" => "ОБНОВЛЕНИЕ СИСТЕМЫ",
            "launch_upd_check" => "Запрос к серверу...",
            "launch_upd_ok" => "Установлена последняя версия.",
            "launch_shut_title" => "ВЫКЛЮЧЕНИЕ",
            "launch_safe" => "Данные сохранены автоматически.\nНажмите ENTER для выхода.",
            "launch_on" => "✓ Система в сети",
            "launch_hint" => "Нажми Q для Выхода",

            // --- Настройки ---
            "settings_title" => "НАСТРОЙКИ",
            "cat_general" => "Общие",
            "cat_eng" => "Инженер и Гонка",
            "cat_units" => "Единицы",
            "cat_alerts" => "Оповещения",
            
            "lang" => "Язык",
            "update_rate" => "Обновление (мс)",
            "history_size" => "История (кадр)",
            "auto_save" => "Авто-сохр.",
            
            "cfg_shift" => "Shift-сигнал",
            "cfg_fuel_safe" => "Запас топлива",
            "cfg_opt_press" => "Цель Давления",
            "cfg_logs" => "Запись логов",
            
            "unit_pressure" => "Давление",
            "unit_temp" => "Температура",
            
            "alert_t_min" => "Мин. Темп. Шин",
            "alert_t_max" => "Макс. Темп. Шин",
            "alert_b_max" => "Макс. Темп. Торм",
            "alert_fuel" => "Мало Топлива",
            "alert_wear" => "Износ Шин",
            
            // --- Общее ---
            "footer_connected" => "ПОДКЛЮЧЕНО",
            "footer_disconnected" => "ОТКЛЮЧЕНО",
            "footer_keys" => "F1-F7: Меню | Q: Выход",
            
            "tab_dash" => "ДАШБОРД",
            "tab_tele" => "ТЕЛЕМЕТРИЯ",
            "tab_eng" => "ИНЖЕНЕР",
            "tab_setup" => "СЕТАП",
            "tab_anal" => "АНАЛИЗ",
            "tab_strat" => "СТРАТЕГИЯ",
            "tab_set" => "НАСТРОЙКИ",
            
            // --- Анализ ---
            "anal_waiting" => "Нет кругов",
            "anal_laps_list" => "История",
            "anal_speed_comp" => "График Скорости",
            "anal_deep" => "Анализ Пилотажа",
            "anal_stability" => "Стабильность",
            "anal_time" => "Время",
            "anal_max_spd" => "Макс",
            "anal_avg_spd" => "Сред",
            "anal_fuel_used" => "Топл.",
            "anal_time_lost" => "Потери",
            "anal_self_title" => "Анализ (Лучший)",
            "lbl_trail" => "Трейл",
            "lbl_coast" => "Накат",
            "lbl_overlap" => "Наложение",
            "lbl_smooth" => "Плавность",
            "lbl_under" => "Снос",
            "lbl_over" => "Занос",
            "lbl_lock" => "Блок",

            // --- Стратегия ---
            "strat_fuel_title" => "Калькулятор",
            "strat_tyres_title" => "Шины",
            "strat_env_title" => "Погода",
            "strat_cons" => "Расх.",
            "strat_laps_rem" => "Ост. кр.",
            "strat_fuel_rem" => "Ост. л.",
            "strat_needed" => "Нужно",
            "strat_delta" => "Дельта",
            "strat_grip" => "Держак",
            "strat_air" => "Возд.",
            "strat_road" => "Асф.",
            "strat_wind" => "Ветер",

            // --- Телеметрия ---
            "graph_speed_rpm" => "Скор/Об",
            "graph_inputs" => "Ввод",
            "graph_gforce" => "G-Force",
            "graph_steering" => "Руль",
            "no_data" => "Жду данные...",
            "tele_friction" => "Круг Сцеп.",
            "tele_car" => "Авто",
            "tele_eng_report" => "Отчет",
            "tele_errors" => "Ошибки",
            "lbl_lat_g" => "Бок G",
            "lbl_lon_g" => "Прод G",
            "lbl_clutch" => "Сцепл",
            "lbl_steer" => "Угол",
            "lbl_pred_lap" => "Прогноз",
            "lbl_fuel_rem" => "Топл",
            "tele_map" => "Карта",
            "tele_map_waiting" => "Проедь круг...",
            "tele_live" => "Инфо",
            
            // --- Дашборд ---
            "dash_tyre_status" => "ШИНЫ",
            "dash_perf" => "ПРОИЗВ",
            "dash_session" => "СЕССИЯ",
            "dash_quick" => "БЫСТРО",
            "avg_press" => "Давл",
            "avg_temp" => "Темп",
            "avg_wear" => "Износ",
            "lbl_speed" => "СКОР",
            "lbl_rpm" => "ОБ/М",
            "lbl_gear" => "ПЕР",
            "lbl_delta" => "ДЕЛ",
            "lbl_throttle" => "ГАЗ",
            "lbl_brake" => "ТОР",
            "lbl_car" => "Авто",
            "lbl_track" => "Трек",
            "lbl_session" => "Сес",
            "lbl_laps" => "Кр",
            "lbl_pos" => "Поз",
            "lbl_fuel" => "Топ",
            "lbl_tc" => "TC",
            "lbl_abs" => "ABS",
            "lbl_map" => "Map",
            
            // --- Инженер ---
            "eng_recs" => "СОВЕТЫ",
            "eng_analysis" => "СТИЛЬ",
            "eng_good" => "Все ок.",
            "eng_push" => "Жми!",
            "eng_action" => "Действие",
            "eng_smooth" => "Плавн",
            "eng_steer" => "Руль",
            "eng_aggr" => "Агр",
            "eng_trail" => "Трейл",
            "eng_lock" => "Блок",
            "eng_spin" => "Букс",
            
            // --- Сетап ---
            "set_list" => "СЕТАПЫ",
            "set_compare" => "СРАВНЕНИЕ",
            "set_param" => "Парам",
            "set_val" => "Знач",
            "set_recom" => "Рек",
            "set_diff" => "Разн",
            "set_no_file" => "Нет файлов",
            "grp_gen" => "ОБЩ",
            "grp_tyres" => "ШИНЫ",
            "grp_aero" => "АЭРО",
            "grp_align" => "ГЕОМ",
            "grp_susp" => "ПОДВ",
            "grp_damp" => "АМОРТ",
            "grp_driv" => "ТРАНС",
            "grp_brake" => "ТОРМ",
            "p_fuel" => "Топл",
            "p_bias" => "Бал",
            "p_limiter" => "Лим",
            "p_press" => "Давл",
            "p_wing" => "Крыл",
            "p_camber" => "Разв",
            "p_toe" => "Схож",
            "p_spring" => "Пруж",
            "p_rod" => "Выс",
            "p_arb" => "Стаб",
            "p_bump" => "Сж",
            "p_reb" => "Отб",
            "p_f_bump" => "Б.Сж",
            "p_f_reb" => "Б.Отб",
            "p_diff_p" => "Диф.Т",
            "p_diff_c" => "Диф.Н",
            "p_gear" => "Пер",
            "p_final" => "Глав",
            
            "view_setup" => "Сетап",
            "view_anal" => "Анализ",
            "view_strat" => "Стратегия",
            "view_tele" => "Телеметрия",
            
            _ => key,
        }.to_string(),
    }
}