-- GENERATED by ac_core::overlay::frame::lua_struct_declaration.
-- Do not edit by hand: `cargo test -p ac_core lua_layout` checks it.
local FRAME_LAYOUT = {
  ac.StructItem.explicit(4, 4),

  version = ac.StructItem.uint32(),
  sequence = ac.StructItem.uint32(),
  speed_kmh = ac.StructItem.float(),
  fuel_litres = ac.StructItem.float(),
  fuel_laps_remaining = ac.StructItem.float(),
  fuel_per_lap = ac.StructItem.float(),
  delta_seconds = ac.StructItem.float(),
  air_temp_c = ac.StructItem.float(),
  road_temp_c = ac.StructItem.float(),
  surface_grip = ac.StructItem.float(),
  tyre_pressure_psi = ac.StructItem.array(ac.StructItem.float(), 4),
  tyre_temp_c = ac.StructItem.array(ac.StructItem.float(), 4),
  tyre_wear_percent = ac.StructItem.array(ac.StructItem.float(), 4),
  brake_temp_c = ac.StructItem.array(ac.StructItem.float(), 4),
  rpm = ac.StructItem.int32(),
  max_rpm = ac.StructItem.int32(),
  gear = ac.StructItem.int32(),
  lap_count = ac.StructItem.int32(),
  last_lap_ms = ac.StructItem.int32(),
  best_lap_ms = ac.StructItem.int32(),
  current_lap_ms = ac.StructItem.int32(),
  position = ac.StructItem.int32(),
  flags = ac.StructItem.uint32(),
  message_count = ac.StructItem.uint32(),
  messages = ac.StructItem.array(ac.StructItem.string(64), 4),
  message_severity = ac.StructItem.array(ac.StructItem.uint32(), 4),
}

return FRAME_LAYOUT
